### ISSUE TITLE
Warning :  findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by nikitaiih** [tjrexer/react-notifications#46]
Getting warning 

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Notification (http://localhost:3003/static/js/vendors~main.chunk.js:87799:5)
    at Transition (http://localhost:3003/static/js/vendors~main.chunk.js:94322:30)
    at CSSTransition (http://localhost:3003/static/js/vendors~main.chunk.js:93439:35)
    at div
    at TransitionGroup (http://localhost:3003/static/js/vendors~main.chunk.js:94891:30)
    at div
    at Notifications (http://localhost:3003/static/js/vendors~main.chunk.js:88565:5)
    at NotificationContainer (http://localhost:3003/static/js/vendors~main.chunk.js:88060:5)
    at div
    at App (http://localhost:3003/static/js/main.chunk.js:196:1)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
findHostInstanceWithWarning @ react-dom.development.js:25406
findDOMNode @ react-dom.development.js:26067
performEnter @ Transition.js:245
updateStatus @ Transition.js:228
componentDidMount @ Transition.js:172
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889

**Comment by greenpeas** [comment]
\+

**Comment by pumbasl** [comment]
`+`

**Comment by codevidhya** [comment]
+

**Comment by Placeblock** [comment]
+

**Comment by marcosdipaolo** [comment]
+

**Comment by invshakil** [comment]
+

**Comment by tjrexer** [comment]
Thanks for the report, sorry for the delay.  Been a busy year plus with Covid & a couple personal things.  Getting back to issues & PRs here now.

Give me a little bit and I'll see if I can get a new major version out in the next couple weeks.

**Comment by v3rron** [comment]
Hi, any ETA on when the update might be available? Thanks

**Comment by AkshatSoodPA** [comment]
`+`

**Comment by alexandre-tobia** [comment]
@tjrexer Hi, any news ?

**Comment by tiennguyen1293** [comment]
.

**Comment by tjrexer** [comment]
I have not been able to find anything causing the warning.  Only warnings I'm seeing is regarding `componentWillX` & am working on that fix.

Check your package-lock, `react-transition-group` should be running on a later version than 4.4.0 (which has historically been the source of this warning).

This is also a duplicate of #21 .

**Comment by D3troit98** [comment]
@tjrexer is it able to work now? Having issues using it with react 18

**Comment by mbasakCinedigmInd** [comment]
the warning is still coming what to do?
