### ISSUE TITLE
Not working with react 18

### ISSUE THREAD

**Issue by mohnark** [tjrexer/react-notifications#67]
```
react_devtools_backend.js:4026 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Notification (http://localhost:3000/static/js/bundle.js:76938:5)
    at Transition (http://localhost:3000/static/js/bundle.js:79562:30)
    at CSSTransition (http://localhost:3000/static/js/bundle.js:78680:35)
    at div
    at TransitionGroup (http://localhost:3000/static/js/bundle.js:80130:30)
    at div
    at Notifications (http://localhost:3000/static/js/bundle.js:77701:5)
    at NotificationContainer (http://localhost:3000/static/js/bundle.js:77198:5)
    at div
    at Alert (http://localhost:3000/main.59cf04c906a101ce3069.hot-update.js:60:164)
    at div
    at Control (http://localhost:3000/static/js/bundle.js:76603:57)
    at UpdatePtsBtn (http://localhost:3000/main.59cf04c906a101ce3069.hot-update.js:162:25)
    at div
    at MapContainerComponent (http://localhost:3000/static/js/bundle.js:92314:21)
    at BaseMap (http://localhost:3000/static/js/bundle.js:489:66)
    at div
    at App
```

**Comment by D3troit98** [comment]
I'm having the same issues. Have you gotten any fix?

**Comment by D3troit98** [comment]
I'm having the same issues. Have you gotten any fixes?

**Comment by D3troit98** [comment]
I'm having the same issues. Have you gotten any fixes?

**Comment by mohnark** [comment]
> I'm having the same issues. Have you gotten any fixes?

I did get it working in StrictMode with React 18, 
Check your implementation in App.js

```
import React, { Component }  from 'react';
import './App.css';
import { ReactNotifications } from 'react-notifications-component'
import 'react-notifications-component/dist/theme.css'

function App() {
  return (
    <div>
    <ReactNotifications />
    <NavBar />
    <BaseMap />
    </div>
  );
}

export default App;

```
